name: "PG Vereinsdatenbank: Build & Push Container Image"

on:
  push:
    branches:
      - main
    paths:
      - 'postgres/**'
      - '.github/workflows/build-container.yml'
      - '.github/workflows/build-pg-verein.yml'

permissions:
  contents: read
  packages: write

jobs:
  get-version:
    runs-on: ubuntu-24.04
    outputs:
      postgres: ${{ steps.postgres_version.outputs.POSTGRES_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Get Postgres version
        id: postgres_version
        run: |
           echo "POSTGRES_VERSION=$(grep -E '^FROM docker.io/library/postgres:[0-9]+\.[0-9]+' postgres/verein.Dockerfile | sed -E 's|.*postgres:([0-9]+\.[0-9]+).*|\1|')" >> $GITHUB_OUTPUT

  call-build-workflow:
    name: Build & Push
    needs: get-version
    uses: erhardtconsulting/relational-databases/.github/workflows/build-container.yml@main
    with:
      context: "postgres"
      dockerfile: "postgres/verein.Dockerfile"
      tag: vereindb-${{ needs.get-version.outputs.postgres }}
      latest: false
      push: true
    secrets: inherit